version: 2.1

orbs:
  python: circleci/python@0.2.1
  heroku: circleci/heroku@1.2.3

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          name: Run unit tests
          command: |
            $HOME/.local/lib/python3.9/site-packages/coverage run -m pytest tests/
            $HOME/.local/lib/python3.9/site-packages/coverage report
            $HOME/.local/lib/python3.9/site-packages/coverage html
      - store_artifacts:
          path: htmlcov

workflows:
  main:
    jobs:
      - build-and-test
      - heroku/deploy-via-git:
          requires:
              - build-and-test
          filters:
              branches:
                only: main


