version: 2.1

orbs:
  python: circleci/python@0.2.1
  heroku: circleci/heroku@1.2.3

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache

workflows:
  main:
    jobs:
      - heroku/deploy-via-git:
          requires:
              - build-and-test
          filters:
              branches:
                only: main


